version: '1.1'
services:
  auth_service:
    build:
      context: .
      dockerfile: './apps/authentication/Dockerfile'
      target: development
    command: ['npm', 'run', 'start:dev', 'authentication']
    container_name: uniqlcoco_authentication_service
    env_file:
      - .env
    ports:
      - '8080:8080'
    volumes:
      - '.:/usr/src/app'
    networks:
      - uniqlcoco_network
  products_service:
    build:
      context: .
      dockerfile: './apps/products/Dockerfile'
      target: development
    command: ['npm', 'run', 'start:dev', 'products']
    container_name: uniqlcoco_products_service
    env_file:
      - .env
    ports:
      - '8081:8081'
    volumes:
      - '.:/usr/src/app'
    networks:
      - uniqlcoco_network
  orders_service:
    build:
      context: .
      dockerfile: './apps/orders/Dockerfile'
      target: development
    command: ['npm', 'run', 'start:dev', 'orders']
    container_name: uniqlcoco_orders_service
    env_file:
      - .env
    ports:
      - '8082:8082'
    volumes:
      - '.:/usr/src/app'
    networks:
      - uniqlcoco_network
  database_service:
    image: uniqlcoco_database:1.0.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    container_name: uniqlcoco_database_service
    volumes:
      - uniqlcoco_db:/var/lib/mysql
    ports:
      - '3307:3306'
    networks:
      - uniqlcoco_network
volumes:
  uniqlcoco_db:
networks:
  uniqlcoco_network:
